version: "3.9"
networks:
  dev:
    driver: bridge
services:
  app: 
    container_name: feip
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - ConnectionString=host=postgres_db;port=5432;database=feipback;username=postgres;password=123;Pooling=true;
    networks:
      - dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: feipback
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: