// <auto-generated />
using Feipder.Tools;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Feipder.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Feipder.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "Куртка",
                            Description = "Куртка зеленая"
                        },
                        new
                        {
                            Id = 2,
                            Article = "Шапка",
                            Description = "Шапка на голову"
                        },
                        new
                        {
                            Id = 3,
                            Article = "Штаны",
                            Description = "Штаны на ноги"
                        },
                        new
                        {
                            Id = 4,
                            Article = "Перчатки",
                            Description = "Перчатки на руки"
                        },
                        new
                        {
                            Id = 5,
                            Article = "Удавка",
                            Description = "Удавка на шею"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
